/* Generated By:JavaCC: Do not edit this line. Linguagem2023Constants.java */
package classes;


/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface Linguagem2023Constants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int PALAVRA_RESERVADA = 16;
  /** RegularExpression Id. */
  int LETRA_MINUSCULA = 17;
  /** RegularExpression Id. */
  int LETRA_MAIUSCULA = 18;
  /** RegularExpression Id. */
  int LETRA = 19;
  /** RegularExpression Id. */
  int ASCII = 20;
  /** RegularExpression Id. */
  int DIGITO = 21;
  /** RegularExpression Id. */
  int UNDERLINE = 22;
  /** RegularExpression Id. */
  int IDENTIFICADOR = 23;
  /** RegularExpression Id. */
  int CONSTANTE_LITERAL = 24;
  /** RegularExpression Id. */
  int CONSTANTE_NUMERICA_INTEIRA = 25;
  /** RegularExpression Id. */
  int CONSTANTE_NUMERICA_REAL_CASAS_DECIMAIS = 26;
  /** RegularExpression Id. */
  int CONSTANTE_NUMERICA_REAL = 27;
  /** RegularExpression Id. */
  int SIMBOLO_ESPECIAL = 28;
  /** RegularExpression Id. */
  int OPERADOR_ARITMETICO = 29;
  /** RegularExpression Id. */
  int OPERADOR_RELACIONAL = 30;
  /** RegularExpression Id. */
  int OPERADOR_LOGICO = 31;
  /** RegularExpression Id. */
  int SIMBOLO_INVALIDO = 32;
  /** RegularExpression Id. */
  int CONSTANTE_LITERAL_INVALIDA = 33;
  /** RegularExpression Id. */
  int CONSTANTE_NUMERICA_INTEIRA_INVALIDA = 34;
  /** RegularExpression Id. */
  int CONSTANTE_NUMERICA_REAL_INVALIDA = 35;
  /** RegularExpression Id. */
  int COMENTARIO_FACULTATIVO_INVALIDO = 36;
  /** RegularExpression Id. */
  int IDENTIFICADOR_INVALIDO = 37;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int COMENTARIO_BLOCO = 1;
  /** Lexical state. */
  int COMENTARIO_LINHA = 2;
  /** Lexical state. */
  int COMENTARIO_FACULTATIVO = 3;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"\\r\\n\"",
    "\"\\n\\r\"",
    "\"/*\"",
    "\"*/\"",
    "<token of kind 10>",
    "\"//\"",
    "<token of kind 12>",
    "<token of kind 13>",
    "\"description\"",
    "<token of kind 15>",
    "<PALAVRA_RESERVADA>",
    "<LETRA_MINUSCULA>",
    "<LETRA_MAIUSCULA>",
    "<LETRA>",
    "<ASCII>",
    "<DIGITO>",
    "\"_\"",
    "<IDENTIFICADOR>",
    "<CONSTANTE_LITERAL>",
    "<CONSTANTE_NUMERICA_INTEIRA>",
    "<CONSTANTE_NUMERICA_REAL_CASAS_DECIMAIS>",
    "<CONSTANTE_NUMERICA_REAL>",
    "<SIMBOLO_ESPECIAL>",
    "<OPERADOR_ARITMETICO>",
    "<OPERADOR_RELACIONAL>",
    "<OPERADOR_LOGICO>",
    "<SIMBOLO_INVALIDO>",
    "<CONSTANTE_LITERAL_INVALIDA>",
    "<CONSTANTE_NUMERICA_INTEIRA_INVALIDA>",
    "<CONSTANTE_NUMERICA_REAL_INVALIDA>",
    "<COMENTARIO_FACULTATIVO_INVALIDO>",
    "<IDENTIFICADOR_INVALIDO>",
  };

}
